server:
  port: 8083
  servlet:
    context-path: /autenticacao
  
spring:
  application:
    name: autenticacao
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#     dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource: 
    url: jdbc:mysql://localhost:3306/microservico-autenticacao?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
    

security:
  jwt:
    token:
      secret-key: chave_microservices    
      expire-length: 360000
          

